### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by rayset** [alexjc/neural-doodle#96]
similar problem of https://github.com/alexjc/neural-doodle/issues/92.

I have a pascal 1070, cuda 8, cudnn 5, theano that works in gpu mode, cuda that works with other programs and path variables configured well. I have the latest drivers.

when I try to run the alias doodle I get this error

`Traceback (most recent call last):
  File "doodle.py", line 85, in <module>
    import theano
  File "/usr/local/lib/python3.4/dist-packages/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/__init__.py", line 697, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/__init__.py", line 495, in use
    device, cuda_initialization_error_message))
OSError: You forced the use of gpu device gpu, but CUDA initialization failed with error:
Unable to get the number of gpus available: CUDA driver version is insufficient for CUDA runtime version
`

in my alias I've put: 

`alias doodle="sudo docker run -v $(pwd)/samples:/nd/samples -v $(pwd)/frames:/nd/frames \
                         -it alexjc/neural-doodle:gpu"
`

for some reason I had to put a sudo in there (even hello world doesn't work without that sudo) and I added '':gpu''.

after I did everything I also ran the nvidia-docker script. same error.

I then updated the script like this:

`# Install dependencies
apt-get update
apt-get install --assume-yes "wget"

# Install Docker Engine
wget --quiet --output-document="-" "https://get.docker.com" | sh
usermod --append --groups="docker" "$SUDO_USER"

# Install an NVIDIA Docker wrapper
NVIDIA_DOCKER="nvidia-docker_1.0.0.rc.3-1_amd64.deb"
NVIDIA_DOCKER_URL="https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/"

wget --directory-prefix="/tmp/" --continue "$NVIDIA_DOCKER_URL/$NVIDIA_DOCKER"
dpkg --install "/tmp/$NVIDIA_DOCKER"
rm --interactive "/tmp/$NVIDIA_DOCKER"

nvidia-docker volume setup`

but no results (he asks me if I've already installed docker tho, and says it may cause problems).

doodle --help works.

**Comment by LazyMammal** [comment]
I got it working (after installing nvidia-docker) with this alias:

`alias doodle="sudo nvidia-docker run -v $(pwd)/samples:/nd/samples -v $(pwd)/frames:/nd/frames -it alexjc/neural-doodle:gpu"`

Only difference is "nvidia-docker" wrapper instead of original "docker" command.

Also ... if you don't want to use "sudo" then add yourself to the [docker group](https://docs.docker.com/engine/installation/linux/ubuntulinux/#/create-a-docker-group):

`sudo usermod -aG docker $USER`

**Comment by thommiano** [comment]
@rayset Did you figure this out? When I use:
`alias doodle="sudo docker run -v $(pwd)/samples:/nd/samples -v $(pwd)/frames:/nd/frames \ -it alexjc/neural-doodle:gpu"`
I can run `doodle --help` without any problems. I run into problems when I try to launch a container with `docker run alexjc/neural-doodle:gpu` or `doodle` which both return the same error as above:
`Traceback (most recent call last): File "doodle.py", line 85, in <module> import theano File "/usr/local/lib/python3.4/dist-packages/theano/__init__.py", line 103, in <module> import theano.sandbox.cuda File "/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/__init__.py", line 697, in <module> use(device=config.device, force=config.force_device, test_driver=False) File "/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/__init__.py", line 495, in use device, cuda_initialization_error_message)) OSError: You forced the use of gpu device gpu, but CUDA initialization failed with error: Unable to get the number of gpus available: CUDA driver version is insufficient for CUDA runtime version`
I tried @LazyMammal alias, but it still returns the same error.
